Added input field to mutations
fs/rails-base-graphql-api pull request #136
Opened 2021-02-15 15:27 UTC by mikhail-kilin

### Summary

For some mutations added input objects

### How it works

The single advantage I found is more simple request from the client side. Now we need to form something like this:
```graphql
mutation SignUp($email: String!, $password: String!, $firstName: String, $lastName: String) {
  signup(email: $email, password: $password, firstName: $firstName, lastName: $lastName) {
    me {
      id
      email
    }
    accessToken
    refreshToken
  }
}
```

With `InputObject` the same request will look like this:
```graphql
mutation SignUp($input: SignupInput!) {
  signup(input: $input) {
    me {
      id
      email
    }
    accessToken
    refreshToken
  }
}
``` 
with query variables:
```graphql
{
  "input": {
	"email": "john.tolkien@example.com",
  	"password": "654321",
  	"firstName": "John",
  	"lastName": "Tolkien"
  }
}
```

### Test plan

None

### Review notes

While reviewing pull-request (especially when it's your pull-request),
please make sure that:

- you understand what problem is solved by PR and how is it solved
- new tests are in place, no redundant tests
- DB schema changes reflect new migrations
- newly introduced DB fields have indexes and constraints
- there are no missed files (migrations, view templates)
- required ENV variables added and described in `.env.example` and added to Heroku
- associated Heroku review app works correctly with introduced changes

### Deploy notes

As I think we need to notify frontend command about changes

### References
* Resolves #93 Issue

2021-02-15 19:22 UTC, EvgeniyEsaulkov requested changes
Would you like to add input object for `SignOut` mutation too?

2021-02-15 19:22 UTC, EvgeniyEsaulkov commented on app/graphql/mutations/presign_data.rb
> +      presign_image = PreparePresignImage.call(input.to_hash)
Can you explain please why did you use here implicit type conversion instead `.to_h`?

2021-02-16 07:14 UTC, mikhail-kilin commented on app/graphql/mutations/presign_data.rb
> +      presign_image = PreparePresignImage.call(input.to_hash)
It was my mistake)

2021-02-16 09:21 UTC, ArthurZaharov commented
@mikhail-kilin this PR will break FE application. Could you coordinate it with them?

2021-02-16 18:34 UTC, EvgeniyEsaulkov requested changes

2021-02-16 18:34 UTC, EvgeniyEsaulkov commented on spec/graphql/mutations/update_password_spec.rb
> +    create(:user, :with_reset_token, id: 111_111, email: "john.doe@example.com", first_name: "John", last_name: "Doe")
As we specified user id here I guess we don't need to call `gsub` method for fixture file:
https://github.com/fs/rails-base-graphql-api/blob/7c25ca8e4f945ffe0dbe70813a3c10ef94ab080e/spec/graphql/mutations/update_password_spec.rb#L37-L39
Instead this we can just hardcode user id within the file

2021-02-17 07:50 UTC, KilinMikhail commented on spec/graphql/mutations/update_password_spec.rb
> +    create(:user, :with_reset_token, id: 111_111, email: "john.doe@example.com", first_name: "John", last_name: "Doe")
fixed

2021-02-17 07:58 UTC, EvgeniyEsaulkov approved these changes

2021-02-25 08:12 UTC, merged