Add bullet gem for catch N+1
fs/rails-base-graphql-api pull request #154
Opened 2021-04-23 15:06 UTC by ArtemMotrych

### Summary

This PR adds bullet gem for detect N+1 queries to db.

### How it works

Screenshots/screencasts of the pull request introduced functionality.
![image](https://user-images.githubusercontent.com/81361107/115891103-6139ef80-a45e-11eb-87e1-9e9167aeb008.png)
Tested by disable RecordLoader in activity type

### Test plan

List of steps to manually test introduced functionality:

* Open GraphiQL App
* Make request using schema:
```
        query {
          activities {
            edges {
              cursor
              node {
                id
                title
                body
                event
                createdAt
                user {
                  id
                  email
                  firstName
                  lastName
                }
              }
            }
            pageInfo {
              endCursor
              startCursor
              hasPreviousPage
              hasNextPage
            }
          }
        }
```
* ...

### Review notes

While reviewing pull-request (especially when it's your pull-request),
please make sure that:

- you understand what problem is solved by PR and how is it solved
- new tests are in place, no redundant tests
- DB schema changes reflect new migrations
- newly introduced DB fields have indexes and constraints
- there are no missed files (migrations, view templates)
- required ENV variables added and described in `.env.example` and added to Heroku
- associated Heroku review app works correctly with introduced changes

### Deploy notes

N\A

### References
* Resolves #### Issue
* [GitHub Pull Request ####](https://github.com/fs/rails-base-graphql-api/pull/####)

2021-04-24 08:12 UTC, EvgeniyEsaulkov requested changes

2021-04-24 08:12 UTC, EvgeniyEsaulkov commented on config/environments/development.rb
> +    Bullet.alert = true
This will pop up a JavaScript alert in the browser. As we have API project without front-end I guess we don't need this option. What do you think?
```suggestion
```

2021-04-24 08:12 UTC, EvgeniyEsaulkov commented on config/initializers/bullet.rb
> +end
Will it raise an error in `production` environment? (because we specified `bullet` gem for `development` and `test` only). Another point - all these options are covered by `environments/development.rb` and `environments/test.rb`. Maybe we can remove this file at all?

2021-05-28 13:32 UTC, ArthurZaharov commented
@ArtemMotrych could we use https://github.com/palkan/n_plus_one_control gem instead of bullet?

2021-07-23 13:10 UTC, closed without merging