Token for confirmation added.
fs/rails-base-graphql-api pull request #165
Opened 2021-06-04 15:17 UTC by MaximovKonstantin

Co-authored-by: AnnaAleynik <anna.mikhaiovna305@gmail.com>, MikhailKilin <mikhail.kilin@flatstack.com>

### Summary

A brief description of the pull request.

### How it works

Screenshots/screencasts of the pull request introduced functionality.

### Test plan

List of steps to manually test introduced functionality:

* Open GraphiQL App
* Make request using schema:
```
  query {
    me: {
      id
      name
    }
  }
```
* ...

### Review notes

While reviewing pull-request (especially when it's your pull-request),
please make sure that:

- you understand what problem is solved by PR and how is it solved
- new tests are in place, no redundant tests
- DB schema changes reflect new migrations
- newly introduced DB fields have indexes and constraints
- there are no missed files (migrations, view templates)
- required ENV variables added and described in `.env.example` and added to Heroku
- associated Heroku review app works correctly with introduced changes

### Deploy notes

Notes regarding deployment the contained body of work.
These should note any db migrations, ENV variables, services, scripts, etc.

### References
* Resolves #### Issue
* [GitHub Pull Request ####](https://github.com/fs/rails-base-graphql-api/pull/####)

2021-07-05 07:21 UTC, EvgeniyEsaulkov requested changes

2021-07-05 07:21 UTC, EvgeniyEsaulkov commented on app/models/possession_token.rb
> +  validates :value, :user_id, presence: true
Do we need to check `user_id` presence as we have `belongs_to :user` association?

2021-07-05 07:21 UTC, EvgeniyEsaulkov commented on .env.example
> +CONFIRM_USER_LINK_TEMPLATE="http://lvh.me:5000/confirm_user?token=%{token_value}"
This link could be different for desktop and mobile users. I guess it's ok for now but in the future maybe it would be better to pass confirmation link with `SignUp` mutation. What do you think?

2021-07-08 11:28 UTC, KilinMikhail commented on app/interactors/create_possession_token.rb
> +  TOKEN_LENGTH = 40
May be it will be better to get this value from env variable?

2021-07-08 11:28 UTC, KilinMikhail commented on app/interactors/create_possession_token.rb
> +  TOKEN_LENGTH = 40
@MaximovKonstantin

2021-07-08 11:30 UTC, KilinMikhail commented on spec/fixtures/json/acceptance/graphql/confirm_user.json
> +}
/n @MaximovKonstantin

2021-07-08 11:34 UTC, KilinMikhail commented on app/models/possession_token.rb
> +  validates :value, :user_id, presence: true
@MaximovKonstantin check value uniqness

2021-07-08 11:35 UTC, KilinMikhail commented on app/interactors/create_possession_token.rb
> +    SecureRandom.hex(TOKEN_LENGTH)
check existing of this value and regenerate if it is not uniq

2021-07-09 17:53 UTC, mikhail-kilin commented on .env.example
> +CONFIRM_USER_LINK_TEMPLATE="http://lvh.me:5000/confirm_user?token=%{token_value}"
> This link could be different for desktop and mobile users. I guess it's ok for now but in the future maybe it would be better to pass confirmation link with `SignUp` mutation. What do you think?

Hmm, but what about the case when I signed up from my phone, but opened email from desktop? As I think confirmation can be realized only on web page and then they will redirect user to mobile app if it is needed

2021-07-14 06:01 UTC, EvgeniyEsaulkov approved these changes

2021-07-23 14:17 UTC, merged